baseurl: /inet-showcases
showallpages: true
data_dir: _docs/_data
includes_dir: _docs/_includes
layouts_dir: _docs/_layouts
exclude: [
"routing/manetprotocols/results"
]

collections:
  docs:
    output: true
    permalink: /:path
